var myString;
var myNum;
var myBool;
var myVar;
// let myArr: string[];
// let myNumber: number[];
// let boolArr: boolean[];
var myArr;
var myNumber;
var boolArr;
var strNumTuple;
myString = "hello string";
myNum = 35;
myBool = true;
myVar = 55;
myArr = ["Milan", "Ivan", "Mia", "Dunja"];
myNumber = [1, 2, 3];
boolArr = [true, false, true];
strNumTuple = ["Hello Mia", 1, 2, 3];
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
console.log(strNumTuple);
